# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6c9bb475c60004d5e8da43b04e1afa33226a6b537b8201b32e41c101a2df9442079dda9cc22462dae622d199c27e69d689f07413cf0682f993f9c580f48e80c4

test:
  secret_key_base: eeda6e9a4dd8260d87fba5ddb89a8a4886b5ae445caffdc11d8105d23f9fb2ab998e09cd9fec5fd6dca7a261f493e0504380d1be99ac73b6a3b0a435c1ac149a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
